version: 2

jobs:
  build:
    docker:
      # see https://circleci.com/docs/2.0/circleci-images/
      # use '-browsers' version to have access to xvfb wrappers
      - image: circleci/node:6.10.3-browsers

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # install pdftops
      - run: sudo apt-get install poppler-utils

      - run: npm test

      - store_artifacts:
          path: build
