apiVersion: v1
kind: Service
metadata:
  name: imageserver
  annotations:
    cloud.google.com/load-balancer-type: "internal"
  labels:
    app: imageserver
spec:
  type: LoadBalancer
  ports:
  - port: 9091
    protocol: TCP
  selector:
    app: imageserver
